name: Auto-version on tag

on:
  push:
    tags:
      - '*'

jobs:
  set_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: \bVersion\s=>\s\"[\d\.]+
          replace: "Version => \"${{ github.ref_name  }}"
          include: "Speedshard_Core.cs"

      - name: Set user info
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit Files & Pull
        run: |
          git commit -a -m "Updated version with CI."
          git pull origin main --rebase

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  create_sml_and_publish:
    runs-on: ubuntu-latest
    needs: [ set_version ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    # Download msp
    - run: dotnet tool install --global ModShardPacker --version 1.0.0
    
    # Run msp and add to release
    - run:  |
      msp -f ${{ github.workspace }} --dll ${{ github.workspace }}/lib
      zip Speedshard_Core.zip ${{ github.workspace }}/Speedshard_Core.sml ${{ github.workspace }}/speedshard.ini
      gh release upload ${{github.event.release.tag_name}} Speedshard_Core.zip